version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - emoji-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - emoji-network

networks:
  emoji-network:
    driver: bridge