services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

networks:
  app-network:
    driver: bridge